NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
FEDERATION_SERVER="https://api.domain.com/federation"
AUTH_SERVER="https://api.domain.com/auth"
TRANSFER_SERVER="https://api.domain.com"
SIGNING_KEY="GBBHQ7H4V6RRORKYLHTCAWP6MOHNORRFJSDPXDFYDGJB2LPZUFPXUEW3"
HORIZON_URL="https://horizon.domain.com"
ACCOUNTS=[
"GD5DJQDDBKGAYNEAXU562HYGOOSYAEOO6AS53PZXBOZGCP5M2OPGMZV3",
"GAENZLGHJGJRCMX5VCHOLHQXU3EMCU5XWDNU4BGGJFNLI2EL354IVBK7",
"GAOO3LWBC4XF6VWRP5ESJ6IBHAISVJMSBTALHOQM2EZG7Q477UWA6L7U"
]
VERSION="2.0.0"


[DOCUMENTATION]
ORG_NAME="VOLC xyz"
ORG_URL="https://volc.xyz"
ORG_LOGO="https://volc.xyz/.well-known/volc.png"
ORG_DESCRIPTION="Volcanic Trading Group"
ORG_KEYBASE="volcxyz"
ORG_TWITTER="volcxyz"
ORG_GITHUB="volcxyz"
ORG_OFFICIAL_EMAIL="volcxyz@sent.com"


[[CURRENCIES]]
code="VOLC"
issuer="GADS43KNEAZ55Z5RQ6SK4WZRQS7QSMWIXBGFV4CPR4HM6XDU73F5NY53"
display_decimals=2
name="VOLC Coin"
desc="There will only ever be 1,000,000,000 VOLC coin existence. We will distribute the bonus share weekly and monthly, check our blog for the schedule".
image="https://volc.xyz/.well-known/volc.png"
fixed_number=1000000000
